name: deid
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - jupyter=1.0.0
  - nose=1.3.7
  - numpy=1.16.3
  - future=0.18.2
  - pandas=0.24.2
  - tqdm=4.32.1
  - nltk=3.4.3
  - mpmath=1.1.0
  - scikit-learn=0.22.1
  - spacy=2.2.2
  - sympy=1.4
  - pillow=6.2.1
  - pytest=4.2.0
  - pytorch=1.1.0
  - tensorboard=1.15.0
  - pip=19.3.1
  - pip:
    - regex==2017.7.28
    - pyarrow==0.13.0
    - DateTime==4.2
    - transformers==2.3.0
    - seqeval==0.0.12
    - stanfordnlp==0.2.0
    - google-cloud-storage==1.29.0
